spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    username: sungho
    password: pass

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true